if(NOT DEFINED SOURCE_FILE OR NOT DEFINED CSD_FILE)
    message(FATAL_ERROR "SOURCE_FILE and CSD_FILE are required")
endif()

file(READ "${SOURCE_FILE}" source_text)
file(READ "${CSD_FILE}" csd_text)

string(REGEX MATCHALL "\\{[ \t]*\"csn[a-z0-9_.]+\"" registered_raw "${source_text}")
set(registered "")
foreach(entry IN LISTS registered_raw)
    string(REGEX REPLACE ".*\"(csn[a-z0-9_.]+)\"" "\\1" name "${entry}")
    list(APPEND registered "${name}")
endforeach()
list(SORT registered)

string(FIND "${csd_text}" "; @covers-begin" covers_begin)
string(FIND "${csd_text}" "; @covers-end" covers_end)
if(covers_begin EQUAL -1 OR covers_end EQUAL -1 OR covers_end LESS covers_begin)
    message(FATAL_ERROR "Missing or invalid @covers inventory in ${CSD_FILE}")
endif()
math(EXPR covers_length "${covers_end} - ${covers_begin}")
string(SUBSTRING "${csd_text}" ${covers_begin} ${covers_length} covers_text)
string(REGEX MATCHALL "csn[a-z0-9_]+(\\.[a-z0-9_]+)*" covered "${covers_text}")

list(LENGTH covered covered_count)
set(covered_unique "${covered}")
list(REMOVE_DUPLICATES covered_unique)
list(LENGTH covered_unique covered_unique_count)
if(NOT covered_count EQUAL covered_unique_count)
    message(FATAL_ERROR "The @covers inventory contains duplicate OENTRY names")
endif()
list(SORT covered_unique)

if(NOT registered STREQUAL covered_unique)
    set(missing "${registered}")
    set(extra "${covered_unique}")
    foreach(name IN LISTS covered_unique)
        list(REMOVE_ITEM missing "${name}")
    endforeach()
    foreach(name IN LISTS registered)
        list(REMOVE_ITEM extra "${name}")
    endforeach()
    message(FATAL_ERROR "i-time signature inventory mismatch; missing=[${missing}], extra=[${extra}]")
endif()

# Dot suffixes are OENTRY dispatch reminders, never public opcode calls.
string(REGEX REPLACE ";[^\n]*" "" executable_csd "${csd_text}")
if(executable_csd MATCHES "csn[a-z0-9_]+\\.[a-z0-9_.]*[ \t]*\\(")
    message(FATAL_ERROR "Dotted csnum opcode call found in executable Csound code")
endif()

list(LENGTH registered registered_count)
message(STATUS "Verified ${registered_count} i-time OENTRY signatures")
