#ifndef CSNUM_INTERNAL_H
#define CSNUM_INTERNAL_H

/* Internal interface between csnum's category translation units.
   Opcode names and signatures remain defined by the OENTRY table in csnum.c. */
#include "csnum.h"
#include <stdint.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#ifndef M_PI_2
#define M_PI_2 (M_PI / 2.0)
#endif

int compare_double_from_array_elem(const void *a, const void *b);
size_t sliding_median_scratch_size(size_t win_size);
const char *get_out_name(OPDS *h);
const char *shape_str(char *buf, size_t buf_size, const uint32_t *shape, uint32_t ndim);
double median_of_scratch(double *scratch, size_t n);
double nearest(double x, double x0, double x1, double y0, double y1);
bool CAN_REUSE_ELEMENTWISE(const K_DATA *k_data, uint32_t handle_a, const CSN_ARRAY *arr_a, uint32_t handle_b, const CSN_ARRAY *arr_b, const CSN_ARRAY *out_arr, double scalar_a, double scalar_b);
bool CAN_REUSE_LAST_RESULT(const K_DATA *k_data, uint32_t source_handle, const CSN_ARRAY *source_arr, const CSN_ARRAY *out_arr);
bool IS_VALID_INDEX(double index);
bool IS_VALID_SHIFT(double shift);
bool IS_VALID_VALUE_INT32(double value);
bool SOURCE_HAS_MOVED(const K_DATA *k_data, uint32_t source_handle, const CSN_ARRAY *arr);
bool is_inarg_i_time(OPDS *h, uint32_t arg_index);
bool BROADCAST_ITER_NEXT(CSN_BROADCAST_ITER *it);
bool AXIS_SLICE_ITER_NEXT(CSN_AXIS_SLICE_ITER *it);
void PUBLISH_DERIVED_RESULT(K_DATA *k_data, uint32_t source_handle, const CSN_ARRAY *source_arr, const CSN_ARRAY *out_arr);
void PUBLISH_ELEMENTWISE(K_DATA *k_data, uint32_t handle_a, const CSN_ARRAY *arr_a, uint32_t handle_b, const CSN_ARRAY *arr_b, const CSN_ARRAY *out_arr, double scalar_a, double scalar_b);
void complex_acos(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_acosh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_asin(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_asinh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_atan(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_atanh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_cos(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_cosh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_exp(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_log(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_scalar_prod(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT a, double b);
void complex_sign(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_sin(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_sinh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_sqrt(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_tan(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void complex_tanh(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT z);
void fill_csnarray(CSN_ARRAY *array, double value);
void fill_csnarray_complex(CSN_ARRAY *array, double re, double im);
void fisher_yates(PCG32_STATE *rng, double *data, size_t size);
void complexdat_to_rect(const COMPLEXDAT *c, double *re, double *im);
void sliding_median_slice(double *dst, const double *src, double *scratch, size_t n, size_t stride, size_t win_size, CSN_MEDIAN_EDGES edge);
int32_t AXIS_ITER_SLICE_INIT(CSN_AXIS_SLICE_ITER *it, const CSN_ARRAY *src, const CSN_ARRAY *dst, uint32_t axis);
int32_t BROADCAST_ITER_INIT(CSN_BROADCAST_ITER *it, uint32_t ndim, const uint32_t *shape, size_t logical_size, const size_t strides[CSN_MAX_BROADCAST_INPUTS][CSN_MAX_DIMS], uint32_t n_inputs);
int32_t ND_ITER_INIT(CSN_BROADCAST_ITER *it, uint32_t ndim, const uint32_t *shape, size_t logical_size, const size_t *strides);
int32_t ND_ITER_SEEK(CSN_BROADCAST_ITER *it, size_t linear_index);
int32_t CHECK_IF_REALLOC_IN(CSOUND *csound, OPDS *h, K_DATA *k_data, CSN_ARRAY *arr, uint32_t source_handle, CSN_SCRATCH *scratch_ref, uint32_t ndim, ITEM_TYPE itype, bool is_value_changed, bool rt_locked);
int32_t CHECK_SELF_ALIAS_CELL_LOCAL(CSOUND *csound, OPDS *h, const K_DATA *k_data, uint32_t source_handle, const CSN_ARRAY *source_arr, uint32_t new_ndim, const uint32_t *new_shape, ITEM_TYPE new_itype);
int32_t BROADCAST_INIT(uint32_t *out_ndim, uint32_t *out_shape, size_t *out_size, size_t out_strides[CSN_MAX_BROADCAST_INPUTS][CSN_MAX_DIMS], const CSN_ARRAY *const sources[], uint32_t n_inputs);
int32_t complex_pow(CSN_COMPLEXDAT *out, CSN_COMPLEXDAT base, CSN_COMPLEXDAT exponent);
int32_t create_csnarray_init(CSOUND *csound,const OPDS *h,uint32_t ndim,const uint32_t *shape,CSN_ARRAY **p_array,CSNREF *p_handle,ITEM_TYPE itype);
int32_t create_empty_csnarray_k_init(CSOUND *csound, CSN_ARR_INIT *p);
int32_t create_full_csnarray_k_init(CSOUND *csound, CSN_FULL *p);
int32_t create_fullcomp_csnarray_k_init(CSOUND *csound, CSN_FULLCOMPLEX *p);
int32_t create_like_csnarray_k_init(CSOUND *csound, CSN_ARR_INIT_LIKE *p);
int32_t create_ones_csnarray_k_init(CSOUND *csound, CSN_ARR_INIT *p);
int32_t create_random_csnarray_k_init(CSOUND *csound, CSN_ARR_RND_INIT *p);
int32_t create_zeros_csnarray_k_init(CSOUND *csound, CSN_ARR_INIT *p);
int32_t csnarray_add_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_add_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_addcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_all_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_all_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_angle_k_init(CSOUND *csound, CSN_ANGLE *p);
int32_t csnarray_any_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_any_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_argmax_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_argmin_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_argselect_k_init(CSOUND *csound, CSN_ARGWHERE *p);
int32_t csnarray_argsort_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_argunique_k_init(CSOUND *csound, CSN_ARGWHERE *p);
int32_t csnarray_argwhere_k_init(CSOUND *csound, CSN_ARGWHERE *p);
int32_t csnarray_atan2_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_atan2_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_atan2_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_clip_in_k_init(CSOUND *csound, CSN_CLIP_IN *p);
int32_t csnarray_clip_k_init(CSOUND *csound, CSN_CLIP *p);
int32_t csnarray_compare_count_k_init(CSOUND *csound, CSN_COUNT *p);
int32_t csnarray_compare_k_init(CSOUND *csound, CSN_COMPARE *p);
int32_t csnarray_complex_to_real_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_compress_k_init(CSOUND *csound, CSN_WHERE_HS *p);
int32_t csnarray_concat_block_k_init(CSOUND *csound, CSN_CONCAT *p);
int32_t csnarray_conj_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_copy_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_cross_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_cumprod_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_cumsum_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_diff_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_distance_k_init(CSOUND *csound, CSN_BINOP_HH_SCALAR *p);
int32_t csnarray_div_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_div_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_div_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_divcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_divcomp_sh_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_SH *p);
int32_t csnarray_divmod_hh_k_init(CSOUND *csound, CSN_DIVMOD_HH *p);
int32_t csnarray_divmod_hs_k_init(CSOUND *csound, CSN_DIVMOD_HS *p);
int32_t csnarray_divmod_sh_k_init(CSOUND *csound, CSN_DIVMOD_SH *p);
int32_t csnarray_dot_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_flip_in_k_deinit(CSOUND *csound, CSN_FLIP_ROLL_IN *p);
int32_t csnarray_flip_in_k_init(CSOUND *csound, CSN_FLIP_ROLL_IN *p);
int32_t csnarray_flip_k_init(CSOUND *csound, CSN_FLIP_ROLL *p);
int32_t csnarray_frame_audio_init(CSOUND *csound, CSN_FRAME_AUDIO *p);
int32_t csnarray_from_audio_init(CSOUND *csound, CSN_FROM_AUDIO *p);
int32_t csnarray_get_col_k_init(CSOUND *csound, CSN_GET_ROWCOL *p);
int32_t csnarray_get_row_k_init(CSOUND *csound, CSN_GET_ROWCOL *p);
int32_t csnarray_get_slice_k_init(CSOUND *csound, CSN_GET_SLICE *p);
int32_t csnarray_gradient_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_head_k_init(CSOUND *csound, CSN_TRUNCATE *p);
int32_t csnarray_hypot_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_hypot_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_identity_k_init(CSOUND *csound, CSN_IDENTITY *p);
int32_t csnarray_imag_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_inner_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_insert_block_deinit(CSOUND *csound, CSN_INSERT_BLOCK *p);
int32_t csnarray_insert_block_k_init(CSOUND *csound, CSN_INSERT_BLOCK *p);
int32_t csnarray_load_k_init(CSOUND *csound, CSN_LOAD *p);
int32_t csnarray_log_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_log_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_log_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_logcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_logcomp_sh_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_SH *p);
int32_t csnarray_logical_and_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_logical_and_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_logical_and_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_logical_or_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_logical_or_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_logical_or_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_max_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_max_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_maximum_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_maximum_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_mean_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_mean_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_meancomp_all_k_init(CSOUND *csound, CSN_REDUCTION_COMPLEX_S *p);
int32_t csnarray_medfilt1d_in_k_init(CSOUND *csound, CSN_MEDFILT_IN *p);
int32_t csnarray_medfilt1d_k_init(CSOUND *csound, CSN_MEDFILT *p);
int32_t csnarray_medfilt_arr_in_k_init(CSOUND *csound, CSN_MEDFILT_ND_ARR_IN *p);
int32_t csnarray_medfilt_deinit(CSOUND *csound, CSN_MEDFILT *p);
int32_t csnarray_medfilt_in_deinit(CSOUND *csound, CSN_MEDFILT_IN *p);
int32_t csnarray_medfilt_in_k_init(CSOUND *csound, CSN_MEDFILT_ND_IN *p);
int32_t csnarray_medfilt_nd_deinit(CSOUND *csound, CSN_MEDFILT_ND *p);
int32_t csnarray_medfilt_nd_in_deinit(CSOUND *csound, CSN_MEDFILT_ND_IN *p);
int32_t csnarray_medfilt_ndarr_deinit(CSOUND *csound, CSN_MEDFILT_ND_ARR *p);
int32_t csnarray_medfilt_ndarr_in_deinit(CSOUND *csound, CSN_MEDFILT_ND_ARR_IN *p);
int32_t csnarray_median_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_median_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_median_scalar_k_deinit(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_min_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_min_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_minimum_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_minimum_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_movmax_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movmax_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_movmean_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movmean_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_movmedian_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movmedian_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_movmin_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movmin_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_movstats_in_k_deinit(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movstd_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movstd_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_movvar_in_k_init(CSOUND *csound, CSN_MOVSTATS_IN *p);
int32_t csnarray_movvar_k_init(CSOUND *csound, CSN_MOVSTATS *p);
int32_t csnarray_mul_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_mul_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_mulcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_norm_k_init(CSOUND *csound, CSN_NORM_REDUCTION *p);
int32_t csnarray_norm_scalar_k_init(CSOUND *csound, CSN_NORM_REDUCTION_SCALAR *p);
int32_t csnarray_normalize_in_k_init(CSOUND *csound, CSN_UNARYOP_AX_IN *p);
int32_t csnarray_normalize_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_ola_audio_deinit(CSOUND *csound, CSN_OLA_AUDIO *p);
int32_t csnarray_ola_audio_init(CSOUND *csound, CSN_OLA_AUDIO *p);
int32_t csnarray_outer_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_pack_audio_init(CSOUND *csound, CSN_PACK_AUDIO *p);
int32_t csnarray_pad_in_k_deinit(CSOUND *csound, CSN_PAD_IN *p);
int32_t csnarray_pad_in_k_init(CSOUND *csound, CSN_PAD_IN *p);
int32_t csnarray_pad_k_init(CSOUND *csound, CSN_PAD *p);
int32_t csnarray_padcomp_in_k_deinit(CSOUND *csound, CSN_PADCOMPLEX_IN *p);
int32_t csnarray_padcomp_in_k_init(CSOUND *csound, CSN_PADCOMPLEX_IN *p);
int32_t csnarray_padcomp_k_init(CSOUND *csound, CSN_PADCOMPLEX *p);
int32_t csnarray_pair_distance_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_perquant_k_init(CSOUND *csound, CSN_PERCQUANT_AX *p);
int32_t csnarray_perquant_s_k_deinit(CSOUND *csound, CSN_PERCQUANT *p);
int32_t csnarray_perquant_scalar_k_init(CSOUND *csound, CSN_PERCQUANT *p);
int32_t csnarray_pop_k_init(CSOUND *csound, CSN_POP_K *p);
int32_t csnarray_popcomp_k_init(CSOUND *csound, CSN_POPCOMPLEX_K *p);
int32_t csnarray_pow_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_pow_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_pow_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_powcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_powcomp_sh_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_SH *p);
int32_t csnarray_prod_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_prod_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_prodcomp_all_k_init(CSOUND *csound, CSN_REDUCTION_COMPLEX_S *p);
int32_t csnarray_project_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_push_k_init(CSOUND *csound, CSN_PUSH_K *p);
int32_t csnarray_pushcomp_k_init(CSOUND *csound, CSN_PUSHCOMPLEX_K *p);
int32_t csnarray_real_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_real_to_complex_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_reflect_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_reject_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_remap_k_init(CSOUND *csound, CSN_REMAP *p);
int32_t csnarray_remap_scalar_k_init(CSOUND *csound, CSN_REMAP_SCALAR *p);
int32_t csnarray_remove_block_k_init(CSOUND *csound, CSN_TAKE *p);
int32_t csnarray_resample_k_init(CSOUND *csound, CSN_RESAMPLE *p);
int32_t csnarray_reshape_in_k_init(CSOUND *csound, CSN_RESHAPE_IN *p);
int32_t csnarray_reshape_k_init(CSOUND *csound, CSN_RESHAPE *p);
int32_t csnarray_resize_in_k_init(CSOUND *csound, CSN_RESIZE_IN *p);
int32_t csnarray_resize_k_init(CSOUND *csound, CSN_RESIZE *p);
int32_t csnarray_reverse_k_init(CSOUND *csound, CSN_UNARYOP *p);
int32_t csnarray_rms_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_rms_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_roll_in_k_init(CSOUND *csound, CSN_FLIP_ROLL_IN *p);
int32_t csnarray_rollaxis_in_k_init(CSOUND *csound, CSN_FLIP_ROLL_IN *p);
int32_t csnarray_save_k_deinit(CSOUND *csound, CSN_SAVE *p);
int32_t csnarray_save_k_init(CSOUND *csound, CSN_SAVE *p);
int32_t csnarray_select_k_init(CSOUND *csound, CSN_ARGWHERE *p);
int32_t csnarray_show_k_deinit(CSOUND *csound, CSN_SHOW *p);
int32_t csnarray_show_k_init(CSOUND *csound, CSN_SHOW *p);
int32_t csnarray_shuffle_k_init(CSOUND *csound, CSN_UNARYOP_IN *p);
int32_t csnarray_sort_in_k_init(CSOUND *csound, CSN_UNARYOP_AX_IN *p);
int32_t csnarray_sort_k_init(CSOUND *csound, CSN_UNARYOP_AX *p);
int32_t csnarray_spaced_space_k_init(CSOUND *csound, CSN_SPACED_SPACE *p);
int32_t csnarray_stack_k_init(CSOUND *csound, CSN_STACK_K *p);
int32_t csnarray_std_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_std_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_sub_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_sub_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_subcomp_all_k_init(CSOUND *csound, CSN_REDUCTION_COMPLEX_S *p);
int32_t csnarray_subtract_hh_k_init(CSOUND *csound, CSN_BINOP_HH *p);
int32_t csnarray_subtract_hs_k_init(CSOUND *csound, CSN_BINOP_HS *p);
int32_t csnarray_subtract_sh_k_init(CSOUND *csound, CSN_BINOP_SH *p);
int32_t csnarray_subtractcomp_hs_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_HS *p);
int32_t csnarray_subtractcomp_sh_k_init(CSOUND *csound, CSN_BINOPCOMPLEX_SH *p);
int32_t csnarray_sum_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_sum_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_sumcomp_all_k_init(CSOUND *csound, CSN_REDUCTION_COMPLEX_S *p);
int32_t csnarray_to_audio_init(CSOUND *csound, CSN_TO_AUDIO *p);
int32_t csnarray_transpose_in_k_deinit(CSOUND *csound, CSN_RESHAPE_IN *p);
int32_t csnarray_transpose_in_k_init(CSOUND *csound, CSN_RESHAPE_IN *p);
int32_t csnarray_truncate_in_k_init(CSOUND *csound, CSN_TRUNCATE_IN *p);
int32_t csnarray_truncate_k_init(CSOUND *csound, CSN_TRUNCATE *p);
int32_t csnarray_unaryop_in_k_init(CSOUND *csound, CSN_UNARYOP_IN *p);
int32_t csnarray_unique_k_init(CSOUND *csound, CSN_COMPARE *p);
int32_t csnarray_unpack_audio_init(CSOUND *csound, CSN_UNPACK_AUDIO *p);
int32_t csnarray_unwrap_angle_in_k_init(CSOUND *csound, CSN_ANGLE_IN *p);
int32_t csnarray_unwrap_angle_k_init(CSOUND *csound, CSN_ANGLE *p);
int32_t csnarray_var_all_k_init(CSOUND *csound, CSN_REDUCTION_SCALAR *p);
int32_t csnarray_var_k_init(CSOUND *csound, CSN_REDUCTION *p);
int32_t csnarray_where_hh_k_init(CSOUND *csound, CSN_WHERE_HH *p);
int32_t csnarray_where_hs_k_init(CSOUND *csound, CSN_WHERE_HS *p);
int32_t csnarray_where_in_hh_k_init(CSOUND *csound, CSN_WHERE_HH_IN *p);
int32_t csnarray_where_in_hs_k_init(CSOUND *csound, CSN_WHERE_HS_IN *p);
int32_t csnarray_window_function_k_init(CSOUND *csound, CSN_WINDOW *p);
int32_t csnarray_wrap_angle_k_init(CSOUND *csound, CSN_ANGLE *p);
int32_t from_array_to_csnarray_k_init(CSOUND *csound, CSN_FROM_ARRAY *p);
int32_t from_complexarray_to_csnarray_k_init(CSOUND *csound, CSN_FROM_ARRAY *p);
int32_t opunary_ax_in_k_deinit(CSOUND *csound, CSN_UNARYOP_AX_IN *p);
int32_t parse_shape_array(CSOUND *csound, const ARRAYDAT *p_shape, uint32_t *out_ndim, uint32_t *out_shape);
int32_t parse_shape_array_k(CSOUND *csound, OPDS *h, const ARRAYDAT *p_shape, uint32_t *out_ndim, uint32_t *out_shape);
int32_t rt_growth_refused(CSOUND *csound, OPDS *perf_h, const CSN_ARRAY *arr, size_t required_size);

#endif
